version: '3.8'
  
services:
  app:
    build: .
    ports:
      - '80'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  
  redis:
    image: redis:7.2-rc2-alpine3.18
    container_name: redis
    ports:
      - '6379:6379'

